name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: php v 8.2
        uses: shivammathur/setup-php@v2
      - name: console commands
        run: |
          php -v
      - name: bye message
        run: echo "bye bye"
