name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: hello message
        run: |
          echo "hello"
          echo "world"
      - name: bye message
        run: echo "bye bye"
