name: First workflow
on: push
jobs:
  project_setup:
    runs-on: ubuntu-latest
    steps:
      - name: get repo code to ubuntu
        uses: actions/checkout@v3
      - name: install composer and npm
        run: |
          composer install
